### ISSUE TITLE
Character escaping inside selectors

### ISSUE THREAD

**Issue by SuggonM** [rrweb-io/CSSOM#9]
Using the [online demo](https://nv.github.io/CSSOM/docs/parse.html), I'm getting this error in browser console when trying to parse a rule with special characters escaped:
```css
.wendy\'s {}
```

```py
parse.js:62 Uncaught 
Error: Unmatched ' (line 1, char 8)
    at parseError (parse.js:62:15)
    at Object.parse (parse.js:110:6)
    at outputUpdated (parse.js:151:19)
    at HTMLTextAreaElement.changed (parse.js:185:2)
```

which is equivalent to this block:
https://github.com/rrweb-io/CSSOM/blob/64dfbde00c7fa3a239ca72c105555dc2b6867361/lib/parse.js#L106-L113

Another minor issue is that, round braces and many other invalid-but-escapable selectors remain unchanged when using `toString()`. Perhaps we could somehow ensure that the returned selector of `toString()` method is always valid?
```css
.wendy(s) {}
```
```js
// current: .wendy(s) {}
// suggestion: .wendy\(s\) {}
CSSOM.parse('.wendy(s) {}').toString();
```

----

I'm trying to parse a fairly large CSS spritesheet that has a lot of these characters, so fixing this would be of huge help!

Another suggestion that *may or may not* be relevant to this repository is, using a CSS escaping module. Mathias has made one in [cssesc](https://github.com/mathiasbynens/cssesc) and it addresses both cases mentioned above, for example [here](https://mothereff.in/css-escapes#0wendy%27s) and [here](https://mothereff.in/css-escapes#0wendy%28s%29).

**Comment by xemlock** [comment]
Same problem is present in the original repo, see NV/CSSOM#118.
